labels:
  - name: e-comm

teams:
  - name: hamilak
    permission: admin  

repository:
  description: E-commerce web application
  topics: javascript, node.js, reactjs, mongodb
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  allow_force_pushes: false

branch_protection:
  restrictions: main
  enforce_admins: true
  required_pull_request_reviews:
    require_code_owner_reviews: true